// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"database/sql"
	"time"
)

type Position struct {
	PositionID string       `db:"position_id"`
	Name       string       `db:"name"`
	UpdatedAt  sql.NullTime `db:"updated_at"`
	CreatedAt  time.Time    `db:"created_at"`
}

type Staff struct {
	StaffID        string         `db:"staff_id"`
	PositionID     string         `db:"position_id"`
	FirstName      string         `db:"first_name"`
	LastName       string         `db:"last_name"`
	Email          string         `db:"email"`
	PasswordHash   []byte         `db:"password_hash"`
	PasswordSalt   []byte         `db:"password_salt"`
	Status         string         `db:"status"`
	SelfieUrl      sql.NullString `db:"selfie_url"`
	SelfieThumbUrl sql.NullString `db:"selfie_thumb_url"`
	UpdatedAt      sql.NullTime   `db:"updated_at"`
	CreatedAt      time.Time      `db:"created_at"`
}
