// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: positions.sql

package repo

import (
	"context"
	"database/sql"
	"time"
)

const CountPositions = `-- name: CountPositions :one
SELECT COUNT(*) FROM positions
`

func (q *Queries) CountPositions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountPositions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreatePosition = `-- name: CreatePosition :exec
INSERT INTO positions (
    position_id,
    name,
    created_at
) VALUES ($1, $2, $3)
`

type CreatePositionParams struct {
	PositionID string    `db:"position_id"`
	Name       string    `db:"name"`
	CreatedAt  time.Time `db:"created_at"`
}

// SQL constants for mutations (used in repository)
func (q *Queries) CreatePosition(ctx context.Context, arg CreatePositionParams) error {
	_, err := q.db.ExecContext(ctx, CreatePosition, arg.PositionID, arg.Name, arg.CreatedAt)
	return err
}

const DeletePosition = `-- name: DeletePosition :exec
DELETE FROM positions
WHERE position_id = $1
`

func (q *Queries) DeletePosition(ctx context.Context, positionID string) error {
	_, err := q.db.ExecContext(ctx, DeletePosition, positionID)
	return err
}

const ExistsPositionByName = `-- name: ExistsPositionByName :one
SELECT EXISTS(
    SELECT 1 FROM positions WHERE name = $1
)
`

func (q *Queries) ExistsPositionByName(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRowContext(ctx, ExistsPositionByName, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const GetPosition = `-- name: GetPosition :one
SELECT position_id, name, updated_at, created_at
FROM positions
WHERE position_id = $1
LIMIT 1
`

func (q *Queries) GetPosition(ctx context.Context, positionID string) (Position, error) {
	row := q.db.QueryRowContext(ctx, GetPosition, positionID)
	var i Position
	err := row.Scan(
		&i.PositionID,
		&i.Name,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const GetPositionByName = `-- name: GetPositionByName :one
SELECT position_id, name, updated_at, created_at
FROM positions
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetPositionByName(ctx context.Context, name string) (Position, error) {
	row := q.db.QueryRowContext(ctx, GetPositionByName, name)
	var i Position
	err := row.Scan(
		&i.PositionID,
		&i.Name,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const ListPositions = `-- name: ListPositions :many
SELECT position_id, name, updated_at, created_at
FROM positions
ORDER BY name
`

func (q *Queries) ListPositions(ctx context.Context) ([]Position, error) {
	rows, err := q.db.QueryContext(ctx, ListPositions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Position{}
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.PositionID,
			&i.Name,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdatePosition = `-- name: UpdatePosition :exec
UPDATE positions
SET
    name = $2,
    updated_at = $3
WHERE position_id = $1
`

type UpdatePositionParams struct {
	PositionID string       `db:"position_id"`
	Name       string       `db:"name"`
	UpdatedAt  sql.NullTime `db:"updated_at"`
}

func (q *Queries) UpdatePosition(ctx context.Context, arg UpdatePositionParams) error {
	_, err := q.db.ExecContext(ctx, UpdatePosition, arg.PositionID, arg.Name, arg.UpdatedAt)
	return err
}
