// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: staffs.sql

package repo

import (
	"context"
	"database/sql"
	"time"
)

const CountStaffs = `-- name: CountStaffs :one
SELECT COUNT(*) FROM staffs
`

func (q *Queries) CountStaffs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountStaffs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountStaffsByStatus = `-- name: CountStaffsByStatus :one
SELECT COUNT(*) FROM staffs WHERE status = $1
`

func (q *Queries) CountStaffsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountStaffsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateStaff = `-- name: CreateStaff :exec
INSERT INTO staffs (
    staff_id,
    position_id,
    first_name,
    last_name,
    email,
    password_hash,
    password_salt,
    status,
    selfie_url,
    selfie_thumb_url,
    created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateStaffParams struct {
	StaffID        string         `db:"staff_id"`
	PositionID     string         `db:"position_id"`
	FirstName      string         `db:"first_name"`
	LastName       string         `db:"last_name"`
	Email          string         `db:"email"`
	PasswordHash   []byte         `db:"password_hash"`
	PasswordSalt   []byte         `db:"password_salt"`
	Status         string         `db:"status"`
	SelfieUrl      sql.NullString `db:"selfie_url"`
	SelfieThumbUrl sql.NullString `db:"selfie_thumb_url"`
	CreatedAt      time.Time      `db:"created_at"`
}

// SQL constants for mutations (used in repository)
func (q *Queries) CreateStaff(ctx context.Context, arg CreateStaffParams) error {
	_, err := q.db.ExecContext(ctx, CreateStaff,
		arg.StaffID,
		arg.PositionID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PasswordHash,
		arg.PasswordSalt,
		arg.Status,
		arg.SelfieUrl,
		arg.SelfieThumbUrl,
		arg.CreatedAt,
	)
	return err
}

const DeleteStaff = `-- name: DeleteStaff :exec
DELETE FROM staffs
WHERE staff_id = $1
`

func (q *Queries) DeleteStaff(ctx context.Context, staffID string) error {
	_, err := q.db.ExecContext(ctx, DeleteStaff, staffID)
	return err
}

const ExistsStaffByEmail = `-- name: ExistsStaffByEmail :one
SELECT EXISTS(
    SELECT 1 FROM staffs WHERE email = $1
)
`

func (q *Queries) ExistsStaffByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, ExistsStaffByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const GetStaff = `-- name: GetStaff :one
SELECT
    staff_id,
    position_id,
    first_name,
    last_name,
    email,
    password_hash,
    password_salt,
    status,
    selfie_url,
    selfie_thumb_url,
    updated_at,
    created_at
FROM staffs
WHERE staff_id = $1
LIMIT 1
`

func (q *Queries) GetStaff(ctx context.Context, staffID string) (Staff, error) {
	row := q.db.QueryRowContext(ctx, GetStaff, staffID)
	var i Staff
	err := row.Scan(
		&i.StaffID,
		&i.PositionID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.PasswordSalt,
		&i.Status,
		&i.SelfieUrl,
		&i.SelfieThumbUrl,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const GetStaffByEmail = `-- name: GetStaffByEmail :one
SELECT
    staff_id,
    position_id,
    first_name,
    last_name,
    email,
    password_hash,
    password_salt,
    status,
    selfie_url,
    selfie_thumb_url,
    updated_at,
    created_at
FROM staffs
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetStaffByEmail(ctx context.Context, email string) (Staff, error) {
	row := q.db.QueryRowContext(ctx, GetStaffByEmail, email)
	var i Staff
	err := row.Scan(
		&i.StaffID,
		&i.PositionID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.PasswordSalt,
		&i.Status,
		&i.SelfieUrl,
		&i.SelfieThumbUrl,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const ListStaffs = `-- name: ListStaffs :many
SELECT
    staff_id,
    position_id,
    first_name,
    last_name,
    email,
    password_hash,
    password_salt,
    status,
    selfie_url,
    selfie_thumb_url,
    updated_at,
    created_at
FROM staffs
ORDER BY created_at DESC
`

func (q *Queries) ListStaffs(ctx context.Context) ([]Staff, error) {
	rows, err := q.db.QueryContext(ctx, ListStaffs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Staff{}
	for rows.Next() {
		var i Staff
		if err := rows.Scan(
			&i.StaffID,
			&i.PositionID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.PasswordHash,
			&i.PasswordSalt,
			&i.Status,
			&i.SelfieUrl,
			&i.SelfieThumbUrl,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListStaffsByPosition = `-- name: ListStaffsByPosition :many
SELECT
    staff_id,
    position_id,
    first_name,
    last_name,
    email,
    password_hash,
    password_salt,
    status,
    selfie_url,
    selfie_thumb_url,
    updated_at,
    created_at
FROM staffs
WHERE position_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListStaffsByPosition(ctx context.Context, positionID string) ([]Staff, error) {
	rows, err := q.db.QueryContext(ctx, ListStaffsByPosition, positionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Staff{}
	for rows.Next() {
		var i Staff
		if err := rows.Scan(
			&i.StaffID,
			&i.PositionID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.PasswordHash,
			&i.PasswordSalt,
			&i.Status,
			&i.SelfieUrl,
			&i.SelfieThumbUrl,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateStaff = `-- name: UpdateStaff :exec
UPDATE staffs
SET
    first_name = $2,
    last_name = $3,
    email = $4,
    password_hash = $5,
    password_salt = $6,
    status = $7,
    selfie_url = $8,
    selfie_thumb_url = $9,
    updated_at = $10
WHERE staff_id = $1
`

type UpdateStaffParams struct {
	StaffID        string         `db:"staff_id"`
	FirstName      string         `db:"first_name"`
	LastName       string         `db:"last_name"`
	Email          string         `db:"email"`
	PasswordHash   []byte         `db:"password_hash"`
	PasswordSalt   []byte         `db:"password_salt"`
	Status         string         `db:"status"`
	SelfieUrl      sql.NullString `db:"selfie_url"`
	SelfieThumbUrl sql.NullString `db:"selfie_thumb_url"`
	UpdatedAt      sql.NullTime   `db:"updated_at"`
}

func (q *Queries) UpdateStaff(ctx context.Context, arg UpdateStaffParams) error {
	_, err := q.db.ExecContext(ctx, UpdateStaff,
		arg.StaffID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PasswordHash,
		arg.PasswordSalt,
		arg.Status,
		arg.SelfieUrl,
		arg.SelfieThumbUrl,
		arg.UpdatedAt,
	)
	return err
}

const UpdateStaffStatus = `-- name: UpdateStaffStatus :exec
UPDATE staffs
SET
    status = $2,
    updated_at = $3
WHERE staff_id = $1
`

type UpdateStaffStatusParams struct {
	StaffID   string       `db:"staff_id"`
	Status    string       `db:"status"`
	UpdatedAt sql.NullTime `db:"updated_at"`
}

func (q *Queries) UpdateStaffStatus(ctx context.Context, arg UpdateStaffStatusParams) error {
	_, err := q.db.ExecContext(ctx, UpdateStaffStatus, arg.StaffID, arg.Status, arg.UpdatedAt)
	return err
}
